@url=[REPLACE URL]

###

POST {{url}}/Processmessage
Content-Type: application/json

{
  "id":3,
  "dt": "2024-09-29T11:51:37.9661049Z",
  "text": "Hello PlatformCon 2024!"
}

###

POST {{url}}/Postmessage
Content-Type: application/json

{
  "id":1,
  "dt": "2024-09-29T11:51:37.9661049Z",
  "text": "Hello PlatformCon 2024!"
}

###
